### ISSUE TITLE
dbf Messy code

### ISSUE THREAD

**Issue by whlysu** [abrman/shp-kit#15]
Chinese garbled characters in dbf files

**Comment by abrman** [comment]
Please provide an example of your code, and or files used.

**Comment by whlysu** [comment]
test(){
      let data = {
        type: "FeatureCollection",
        features: [
          {
            type: "Feature",
            properties: { name: "Point A" ,name_cn: "中文 A" ,},
            geometry: {
              type: "Point",
              coordinates: [120.0, 30.0],
            },
          },
        ],
      };
    shpWriteZip("name",data,"Point",{},true)
    },

**Comment by whlysu** [comment]
Dbf.ts  :

import createDataView from "../helpers/createDataView"; 

type FieldMeta = {
  field_key: string;
  field_name: string;
  field_type: "C" | "N" | "L";
  field_length: number;
  field_decimal_length: number;
};

type Properties = { [key: string]: string | number | boolean | object | any[] }[];

/**
 * 截取字符串，确保按字节长度处理 UTF-8 编码
 */
const truncateByByte = (input: string, maxLength: number) => {
  let byteCount = 0;
  let result = "";
  for (const char of input) {
    const charLength = new TextEncoder().encode(char).length; // 计算 UTF-8 编码下的字节长度
    if (byteCount + charLength > maxLength) break;
    byteCount += charLength;
    result += char;
  }
  return result;
};

/**
 * 格式化字符串字段
 */
const formatStringField = (input: string, len: number) => {
  const truncatedString = truncateByByte(input, len);
  const remainingSpaces = Math.max(0, len - new TextEncoder().encode(truncatedString).length);
  return truncatedString + " ".repeat(remainingSpaces);
};

/**
 * 格式化数值字段
 */
const formatNumField = (input: number, len: number, decimalSpaces: number) => {
  const formattedNumber = input.toFixed(decimalSpaces);
  const remainingSpaces = Math.max(0, len - formattedNumber.length);
  return " ".repeat(remainingSpaces) + formattedNumber;
};

/**
 * 获取字段元数据
 */
const getMeta = (properties: Properties) => {
  const fieldsMetaObject: { [key: string]: FieldMeta } = {};
  properties.forEach((props) => {
    Object.keys(props).forEach((key) => {
      const value = props[key];
      if (typeof value === "boolean") {
        if (!fieldsMetaObject[key]) {
          fieldsMetaObject[key] = {
            field_key: key,
            field_name: key,
            field_type: "L",
            field_length: 1,
            field_decimal_length: 0,
          };
        }
      } else if (typeof value === "string") {
        const encodedLength = new TextEncoder().encode(value).length;
        if (!fieldsMetaObject[key]) {
          fieldsMetaObject[key] = {
            field_key: key,
            field_name: key,
            field_type: "C",
            field_length: Math.min(254, encodedLength),
            field_decimal_length: 0,
          };
        } else {
          fieldsMetaObject[key].field_length = Math.min(
              254,
              Math.max(encodedLength, fieldsMetaObject[key].field_length)
          );
        }
      } else if (typeof value === "number") {
        const decimal = String(value).split(".")[1]?.length || 0;
        const length = String(value).length;
        if (!fieldsMetaObject[key]) {
          fieldsMetaObject[key] = {
            field_key: key,
            field_name: key,
            field_type: "N",
            field_length: length,
            field_decimal_length: decimal,
          };
        } else {
          fieldsMetaObject[key].field_length = Math.max(length, fieldsMetaObject[key].field_length);
          fieldsMetaObject[key].field_decimal_length = Math.max(decimal, fieldsMetaObject[key].field_decimal_length);
        }
      }
    });
  });

  const fieldsMeta = Object.values(fieldsMetaObject);
  const recordLength = fieldsMeta.reduce((sum, field) => sum + field.field_length, 1); // 每条记录前有 1 个字节标记是否删除

  return { fieldsMeta, recordLength };
};

/**
 * 根据 GeoJSON 数据生成 DBF 文件
 */
const generateDbf = (records: { [key: string]: string | number | boolean | object | any[] }[]) => {
  const { fieldsMeta, recordLength } = getMeta(records);

  const fileByteLength =
      32 + // Header
      32 * fieldsMeta.length + // Field descriptors
      1 + // Header terminator
      recordLength * records.length + // Records
      1; // End-of-file marker

  const dbfView = createDataView(fileByteLength);
  dbfView.setUint8(fileByteLength - 1, 26); // End-of-file marker

  // Set DBF header
  dbfView.setUint8(0, 3); // DBF file version
  const now = new Date();
  dbfView.setUint8(1, now.getFullYear() - 1900);
  dbfView.setUint8(2, now.getMonth() + 1);
  dbfView.setUint8(3, now.getDate());
  dbfView.setInt32(4, records.length, true); // Record count
  dbfView.setInt16(8, 32 + fieldsMeta.length * 32 + 1, true); // Header length
  dbfView.setInt16(10, recordLength, true); // Record length
  dbfView.setUint8(29, 0x30); // 0x30, Standard ASCII encoding

  // Write field descriptors
  fieldsMeta.forEach((field, i) => {
    const offset = 32 + i * 32;
    for (let j = 0; j < 10; j++) {
      dbfView.setUint8(offset + j, field.field_name.charCodeAt(j) || 0);
    }
    dbfView.setUint8(offset + 11, field.field_type.charCodeAt(0));
    dbfView.setUint8(offset + 16, field.field_length);
    dbfView.setUint8(offset + 17, field.field_decimal_length);
  });

  dbfView.setUint8(32 + fieldsMeta.length * 32, 13); // Header terminator

  // Write records
  const recordStart = 32 + fieldsMeta.length * 32 + 1;
  records.forEach((record, recordIndex) => {
    let recordOffset = 1;
    dbfView.setUint8(recordStart + recordIndex * recordLength, 0x20); // Active record marker
    fieldsMeta.forEach((field) => {
      const value = record[field.field_key];
      if (field.field_type === "C") {
        const stringValue = formatStringField(value as string, field.field_length);
        const encodedValue = new TextEncoder().encode(stringValue);
        for (let i = 0; i < field.field_length; i++) {
          dbfView.setUint8(recordStart + recordIndex * recordLength + recordOffset + i, encodedValue[i] || 0x20);
        }
      } else if (field.field_type === "N") {
        const numberValue = formatNumField(
            value as number,
            field.field_length,
            field.field_decimal_length
        );
        for (let i = 0; i < numberValue.length; i++) {
          dbfView.setUint8(recordStart + recordIndex * recordLength + recordOffset + i, numberValue.charCodeAt(i));
        }
      }
      recordOffset += field.field_length;
    });
  });

  return dbfView;
};

export default generateDbf;

**Comment by abrman** [comment]
Thank you for bringing this to my attention and providing a solution.
Fixed in [v0.4.0](https://github.com/abrman/shp-kit/releases/tag/v0.4.0).
